### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Seiori** [sundowndev/PhoneInfoga#100] opened 2019-07-22 04:18 UTC
**Describe the bug**
Bug appears after I have answered if I want to format the number.

**To Reproduce**
I ran "python3 phoneinfoga.py -n (number)"

**Expected behavior**
I expected to be met with links/information found relating to the number I entered.

**Screenshots (optional)**
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/mnt/c/WINDOWS/system32/phoneinfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/mnt/c/WINDOWS/system32/phoneinfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/nesja/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/nesja/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/nesja/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/nesja/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/nesja/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Desktop (please complete the following information):**
 - OS: Windows 10 - Running Ubuntu 1804.2019.521.0
 - Python Version: "python --version Python 2.7.15+" "python3 --version Python 3.6.8"

**Additional context**

**Comment by sundowndev** [comment] 2019-08-13 16:53
Sorry for the late response, do you have Firefox installed ?

**Comment by sundowndev** [comment] 2019-08-13 16:54
Duplicate of #91

**Closed by sundowndev** 2019-08-13 16:54 UTC
