### ISSUE TITLE
Selenium webdriver : Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by captin-owesome** [sundowndev/PhoneInfoga#104] opened 2019-07-29 17:14 UTC
root@*****:/home/t/Downloads/PhoneInfoga# python3 phoneinfoga.py -n +8801*******2 --recon
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 8801xxxxxxxx2 ---- [!]
[*] Running local scan...
[+] International format: +880 18xxxxxxxx2
[+] Local format: 18xxxxxxxx
[+] Country found: Bangladesh (+880)
[+] City/Area: Bangladesh
[+] Carrier: Robi
[+] Timezone: Asia/Dhaka
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+880) 018xxxxxxxx2
[+] Country: Bangladesh (People's Republic of) (BD)
[+] Location: 
[+] Carrier: xxxxxxxLtd
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for +8800xxxxxxx2
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/t/Downloads/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/t/Downloads/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Rosenb90** [comment] 2019-08-13 16:44
I was having the same issue, then I downloaded Mozilla FireFox and it worked!
Hope this helps.

**Comment by sundowndev** [comment] 2019-08-13 16:54
Duplicate of #91

**Closed by sundowndev** 2019-08-13 16:54 UTC

**Comment by tofa7** [comment] 2019-08-14 03:16
Run from root account
