### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION= In phoneInfoga

### ISSUE THREAD

**Issue by Abhijithm41851** [sundowndev/PhoneInfoga#391] opened 2020-06-16 06:24 UTC
when we scanning a mobile number after ovh scan this problem will found

**Comment by Abhijithm41851** [comment] 2020-06-16 06:25
Need help ? Read https://github.com/sundowndev/PhoneInfoga/wiki

GOOGLE_ABUSE_EXEMPTION=^

**Comment by Devil-vx** [comment] 2020-06-16 10:48
What is this v1 label can u tell me because for me too it occurred same issue

**Comment by commandoskeepz** [comment] 2020-08-18 10:54
please i am having the same issue and i don't know how to get past this GOOGLE_ABUSE_EXEMPTION. please help

**Comment by sundowndev** [comment] 2020-08-18 19:32
Duplicate of #399

**Closed by sundowndev** 2020-08-18 19:32 UTC
Labels: legacy (v1.x)

**Comment by Snake10q4** [comment] 2022-10-09 17:15
I am having the same problem. Thanks for the help
