### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION

### ISSUE THREAD

**Issue by uianon** [sundowndev/PhoneInfoga#54] opened 2019-06-01 04:15 UTC
(!) You are temporary blacklisted from Google search.
how i get this ?

**Comment by eliddell1** [comment] 2019-06-01 14:23
the wiki tells you exactly what this is and how to fix it.  Unfortunately for me, I am not able to get the GOOGLE_ABUSE_EXEMPTION cookie.  No matter how many time i clear my cache, delete cookies, change the request, do a hard refresh, no such named cookie appears.. is it possible google has change the name of the cookie?

**Comment by fy5ve** [comment] 2019-06-01 15:10
Quick fix https://github.com/sundowndev/PhoneInfoga/issues/6#issuecomment-497952054

**Comment by sundowndev** [comment] 2019-06-01 19:36
Duplicate of #6

**Closed by sundowndev** 2019-06-01 19:36 UTC
Labels: duplicate

**Comment by bhardwajrishav** [comment] 2020-05-03 14:39
Nice
