### ISSUE TITLE
Session Not Created Exception "Unable to find a matching set of capabilities"

### ISSUE THREAD

**Issue by ReztDev** [sundowndev/PhoneInfoga#99] opened 2019-07-18 07:04 UTC
___ _                       _____        __
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 6xxxxxxxxx ---- [!]
[*] Running local scan...
[+] International format: +6xxxxxxxxx
[+] Local format: 8xxxxxxxxx
[+] Country found: Indonesia (+62)
[+] City/Area: Indonesia
[+] Carrier: Telkomsel
[+] Timezone: Asia/Jakarta
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+62) xxxxxxxxx
[+] Country: Indonesia (Republic of) (ID)
[+] Location:
[+] Carrier: PT Telekomunikasi Selular (TELKOMSEL)
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for +6xxxxxxxxxx
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/mnt/e/tools_security/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/mnt/e/tools_security/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox(executable_path="/usr/bin/geckodriver")
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: **Unable to find a matching set of capabilities**

**Comment by greycr0w** [comment] 2019-07-20 09:06
Same issue here.

**Comment by sundowndev** [comment] 2019-08-13 16:53
Do you have Firefox installed ?

**Comment by sundowndev** [comment] 2019-08-13 16:54
Duplicate of #91

**Closed by sundowndev** 2019-08-13 16:54 UTC
