### ISSUE TITLE
Says this!

### ISSUE THREAD

**Issue by thalfpant** [sundowndev/PhoneInfoga#79] opened 2019-06-11 15:52 UTC
[!] ---- Fetching informations for 880172728xxxx ---- [!]
[*] Running local scan...
[+] International format: +880 1727-28xxxx
[+] Local format: 172728xxxx
[+] Country found: Bangladesh (+880)
[+] City/Area: Bangladesh
[+] Carrier: Grameenphone
[+] Timezone: Asia/Dhaka
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+880) 0172728xxxx
[+] Country: Bangladesh (People's Republic of) (BD)
[+] Location:
[+] Carrier: GrameenPhone Ltd (GP)
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/880-1727-28xxxx
Would you like to use an additional format for this number ? (y/N) N
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "C:\Users\XooT\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\XooT\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\XooT\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "C:\Users\XooT\PhoneInfoga\scanners\footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "C:\Users\XooT\PhoneInfoga\lib\googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "C:\Users\XooT\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\XooT\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment] 2019-06-11 16:44
It seems you didn't installed geckodriver properly. See [this comment on stackoverflow](https://stackoverflow.com/a/40437690).

1. What command did you run ?
2. What is your OS ?
3. Do you have the latest version of Firefox installed ?

**Comment by MarcusCS** [comment] 2019-06-15 14:02
I have solved it by just downloading geckodriver and copy-pasting it in the directory where your actual program exists.

**Comment by PsyPython** [comment] 2019-07-06 01:05
Do you path the genkodrive folder?
`export PATH=$PATH:/path-to-extracted-file/.`

**Comment by sundowndev** [comment] 2019-07-12 13:18
Try this https://github.com/sundowndev/PhoneInfoga/issues/84#issuecomment-508943051

**Comment by sundowndev** [comment] 2019-07-12 13:20
Duplicate of #84

**Closed by sundowndev** 2019-07-12 13:20 UTC
Labels: missing details
