### ISSUE TITLE
Error when I start

### ISSUE THREAD

**Issue by DEDHACKS** [sundowndev/PhoneInfoga#95] opened 2019-07-12 20:02 UTC
Hello, I just tried your software, and I got that :

`Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/dedhacks/Documents/tool/Social/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/dedhacks/Documents/tool/Social/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

**Comment by sundowndev** [comment] 2019-07-16 15:41
Duplicate of #91

**Closed by sundowndev** 2019-07-16 15:41 UTC

**Comment by countermental** [comment] 2024-04-08 19:32
while i was running docker it said after i ran the command " docker run -it sundowndev/phoneinfoga scan -n" and typed the number , "
unknown command "71" for "phoneinfoga scan"
