### ISSUE TITLE
Google captcha is not handled properly

### ISSUE THREAD

**Issue by nevoodoo** [sundowndev/PhoneInfoga#6] opened 2018-12-10 14:21 UTC
The program gave me a captcha link which I believe is in the format `"https://www.google.com/search?tbs=li:1&q=xxxxxxxxxxxx | intext:"xxxxxxxxxxxx" | intext:"xxxxxxxxxxxx" | intext:"xxxx xxx xxx"&amp;gws_rd=ssl"` not sure if I'm looking at the wrong thing or not but when I paste that into the URL bar, there is no CAPTCHA and obviously no cookie by the name GOOGLE_ABUSE_EXEMPTION.

Let me know,

Thanks

**Comment by sundowndev** [comment] 2018-12-10 16:42
Hi, sometime you just need to refresh the page. Can you try and tell me ?

I'll look into a way to get the captcha 100% of time (using a very odd looking request).

**Comment by The-legend3** [comment] 2018-12-15 22:42
Having the same issue. Any ideas?

**Comment by sundowndev** [comment] 2018-12-16 13:48
@The-legend3 Again, did you try refreshing the Google page to have the cookie created ?

**Comment by sundowndev** [comment] 2018-12-31 12:18
Feel free to reopen if you have further details about that Google captcha behavior.

**Comment by deadfishhackers** [comment] 2019-02-20 07:45
help

**Comment by sundowndev** [comment] 2019-02-20 09:53
Without details I'll not be able to help you.

Read the wiki about [dealing with Google captcha](https://github.com/sundowndev/PhoneInfoga/wiki/Dealing-with-Google-captcha#troubleshooting)

**Comment by federico33385** [comment] 2019-04-29 18:43
Dear All, 

I can confirm that this is not working, Google Chrome, Firefox, Developer tools. 

Looked at:

Session Storage
Local Storage, 
Any other Storage available in there :-)

There seems to nos be a reliable way to get this cookie name to show up. You cannot trigger this cookie by just keeping F5 pressed and firing the refresh hundred of times.

**Comment by sundowndev** [comment] 2019-04-30 07:19
@federico33385 Did you try using private browsing ?

**Comment by Smacksmack206** [comment] 2019-05-29 20:58
I can confirm i'm having issues getting the captcha to show up as well. i tried using different browsers from you saying something about user agent, also tried using incognito/private mode in the browser too

**Comment by sundowndev** [comment] 2019-05-31 08:20
@Smacksmack206 Can you please give me :

- Your country
- The exact URL the tool ask you to visit (hide your IP and phone number)
- The exact URL google redirects you to, if it's not the same (hide your IP and phone number)
- Your complete user-agent
- A screenshot of what cookie you have in browser storage (just the keys, not the values)

Other people in this topic can do it too, also you can send it by email if you don't want it to be public `raphael[at]crvx.fr`.

Thank you for your help on this!

**Comment by fy5ve** [comment] 2019-06-01 15:05
I had the same issue, but found a solution that worked for me:

Turn on a VPN, use the Brave's tor browser not the "incognito" with (option + command + N)

Paste the link and solve the robot verification then once you finish, hit right click > inspect > Application > Cookies
You should find it in the first file this time. copy the value and paste it in the terminal.

**Comment by fy5ve** [comment] 2019-06-01 15:41
Worth to mention that after few times trying this method with success i get this message on the captcha box 

> our computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

**Comment by surrealalucard** [comment] 2019-06-02 00:53
I am also having this issue. Get blacklisted and given a URL to go to, when I manually paste into browser (tried chromium and firefox, there is no captcha or cookie. Tried both in regular and incognito browsing.
**Country**: United States
**URL** (Both url given and redirect was here. Also * = phone number input): https://www.google.com/search?tbs=li:1&q=**********+OR+%22**********%22+OR+%22%2B*+***-***-****%22&amp;gws_rd=ssl&amp;gl=us
**User Agent**: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
**Cookies in Browser**: 
1P_JAR
ANID
NID
CGIC
DV
SNID

**Comment by eliddell1** [comment] 2019-06-02 16:05
For me part of my problem was that I was running anonsurf and it kept changing my ip.  turning off TOR solved it..

**Comment by sundowndev** [comment] 2019-06-02 18:50
Here's the main problem: the tool doesn't have the same identity than your browser. I'm investigating on how to properly trigger Google captcha and get a whitelist cookie that was created for this identity. Using Selenium driver would be a good idea, especially to automatically open the captcha URL and get the cookie. I actually don't have much spare time so it will take me some time to fix this, but if you're up to help me on this, feel free to participate on this topic or by sending me an email (raphael[at]crvx.fr).

Also I think the fact that the tool works perfectly for me is -probably- because the identity I set to the tool to querying Google is optimized to my browser identity (IP address, HTTP headers, user-agent ...). I found out that sometimes, even when both browser and tool are blacklisted and asked to complete the captcha, the cookie given by the browser after solving the captcha is not working on the tool because the cookie is not compatible with the tool web identity. So the goal now is to find a way to querying and solve the captcha with the exact same web identity.

I see two options to make this possible :
- Keep querying Google with the request library and use a web driver such as selenium with custom request settings, to fit with the initial request
- Use a web driver for both querying Google and solving captcha, that means the web driver must have an API to both manipulate HTML elements and request settings

**Comment by YaakovForte** [comment] 2019-06-03 12:47
so I hope this will help someone here.

so I had the same problem with captcha and I tried everything and none worked for me so what I did I simply searched for it on chrome and it give me the thing that u need to verify that ur, not a robot and then after I finish doing that I gat the GOOGLE_ABUSE_EXEMPTION thing so know I am happy good luck to every one.

**Comment by lyrip** [comment] 2019-06-03 21:53
I was having the issue first all i did is just open the link in Tor and i got the captcha and the cookie but for some reason the cookie isnt working whenever i use it gives me the whole google abuse exemption message again(i tried clearing my cookies and cache same result)

**Comment by scrblrus** [comment] 2019-06-04 08:22
What you need to do to fix this is to use cURL instead of clicking the link as you normally would. This will give you the cookie. I did this in Firefox. 

Follow these steps:

1. Follow the link as the the PhoneInfoga tool tells you to. I used ctrl + click to open it in a new tab in Firefox. 
2. Press F12 to bring up developer mode (or use whatever key your browser specifies)
3. Go to the tab that says "network."
4. Look for something that says POST under the method column. Now right click on the row with POST in it. This is the request you made earlier. It should be at the top. When you right click this, it will say something like "copy" with an option to copy as cURL. Copy it as cURL.
5. Now that you've copied the text, go to your terminal and open a new tab. Paste the cURL text into the terminal. It should automatically execute. Once that is done, you need to look for something in the output that says 'Cookie: 1P_JAR=2019-xx-xx-xx'.
6. Paste the part of the text starting after Cookie: (in this example, 1P_JAR=2019-xx-xx-xx) into the PhoneInfoga request for the code. 
From our previous example: GOOGLE_ABUSE_EXEMPTION=1P_JAR=2019-xx-xx-xx
7. Hit enter

This should trigger the tool to continue running properly. If anyone knows why this works, or can verify that they had the same result, let me know. I just about tried everything and this was the only fix I came up with.

**Comment by lyrip** [comment] 2019-06-04 14:51
so i tried it again today and everything was working normally i even got the captcha this time on firefox didnt even need tor and all is good so maybe if someone still having the issue try restarting your pc and modem

**Comment by ChrisKls** [comment] 2019-06-04 16:57
Dear all, 
I can confirm the issue : same problem here.

Country : France
URL : https://www.google.com/search?:tbs=li:1&q=337******49+OR+%22337******49%22+OR+%22%2B33+7+**+**+**+49%22&amp;gws_rd=ssl&amp;gl=us
I tried an other phone number with the same result. 

There was no redirection when I pasted the link (for what I can tell). I tried it on Firefox, Chrome and TOR, refreshed multiple times and got my PC rebooted. Still no GOOGLE_ABUSE_EXEMPTION value to copy appeared. I got no captcha to solve. 

My Firefox user-agent is : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

The storage/cookie values available are : 1P_JAR, ANID, CGIC (x2), CONSENT, DV, NID and SNID.

Thx for the job you made, hope it helps !

**Comment by JBGitHub11** [comment] 2019-06-05 17:09
api and cx are required in config.py, right?

**Comment by sundowndev** [comment] 2019-06-05 18:12
@JBGitHub11 No, this is optional if you want to use your own Google API key. I recommend doing this to avoid having this issue.

**Comment by mirukusheki** [comment] 2019-06-06 01:12
> @JBGitHub11 No, this is optional if you want to use your own Google API key. I recommend doing this to avoid having issues with Google captcha.

How to get google_api_key and cx_id?

**Comment by ThatWeirdAndrew** [comment] 2019-06-06 01:16
@mirukusheki There is a great guide here: https://datasploit.readthedocs.io/en/latest/apiGeneration/

instead of typing pastebin.com and pastie.org, type in google.com.

**Comment by mirukusheki** [comment] 2019-06-06 01:32
> @mirukusheki There is a great guide here: https://datasploit.readthedocs.io/en/latest/apiGeneration/
> 
> instead of typing pastebin.com and pastie.org, type in google.com.

It works now without any captcha verification. thank you

**Comment by mirukusheki** [comment] 2019-06-06 01:44
I already updated the comment. It looks like something wrong with the API Code

**Comment by sundowndev** [comment] 2019-06-06 09:47
@mirukusheki @ThatWeirdAndrew See https://github.com/sundowndev/PhoneInfoga/issues/50#issuecomment-499426584

**Comment by Th3-Think3r** [comment] 2019-06-06 15:16
Still having the same issue as many others. Have tried Chrome, incognito, FF, Tor, none of them gave me the captcha option

**Comment by scrblrus** [comment] 2019-06-06 18:01
I have the same issue. I thought I had a workaround, but couldn't reproduce it.

I'd prefer not to use Google's api since they are not friendly to privacy concerns and it's not free.

Can we implement a privacy and security oriented search api instead?

**Comment by scrblrus** [comment] 2019-06-06 20:24
I have an update. I don't know if this will help, but I'm working on reproducing it. It still slows down the scanning process, but may be a workaround at this time. I'm using Firefox. What I did to get to force the Captcha to appear was I went into the address bar and clicked enter over and over as if I was doing the same search multiple times. I did this extremely fast. It was rather annoying, but the Captcha eventually appeared. I solved the Captcha and the cookie appeared. In the developer menu, I grabbed the text that starts with ID=xxxxxxxxxxxxx a really long string. You then paste that into your terminal and it should work.

**Comment by mikediachenko** [comment] 2019-06-07 07:56
@scrblrus Hi. Interesting tip. I will try it today, because I was fighting to get Captcha for days with no results.

**Comment by Th3-Think3r** [comment] 2019-06-07 14:08
@scrblrus I actually was trying that with Chrome and Tor and I still never made CAPTCHA appear. Its amazing, they appear in the most inconvenient instances just not the one time you actually want them.

**Comment by scrblrus** [comment] 2019-06-07 17:43
@Th3-Think3r @mikediachenko I could use some help reproducing this workaround. Another note, once you get the code, immediately copy and paste it into a document to save it. I was able to use the same code after running the script on another device successfully. I hope we find a more permanent fix, soon.

**Comment by kiroxxvx** [comment] 2019-06-08 03:12
When I open the Captcha link from terminal (Firefox), I get brought to an search that has results, there is no captcha or anything but the page itself isn't blank. I am not using a VPN.

**Comment by scrblrus** [comment] 2019-06-08 06:39
@kiroxxvx That is the same behavior I experienced. Look at my previous post. The search results don't matter. Stay on that page. What you need is to trigger the CAPTCHA. I described earlier how to do this. Stay on that page and follow the steps I posted earlier.

**Comment by sundowndev** [comment] 2019-06-08 10:51
We have enough information about this issue. Locked until it get a fix, I'm working on it.

**Comment by sundowndev** [comment] 2019-06-10 17:34
We now have a fix for this issue using Selenium. Can everyone try it and tell me ?

In a previous installation, follow these steps :

- Checkout to the develop branch : `git checkout develop`
- Install the requirements again : `python3 -m pip install -r requirements.txt`
- Install the geckodriver
- Run the tool as usual

#### How to install geckodriver on Linux

```shell
wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
tar xvfz geckodriver-v0.24.0-linux64.tar.gz
sudo mv geckodriver /usr/bin
```

Tested on a fresh install of *Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux* with *Python 3.7.3*.

**Comment by Th3-Think3r** [comment] 2019-06-10 21:04
Im having the same issue as before after following steps above.

**Comment by sundowndev** [comment] 2019-06-10 21:08
@Th3-Think3r It's not possible. I forgot to mention that you need to pull the new code, `git checkout develop` then `git pull`.

**Comment by Th3-Think3r** [comment] 2019-06-10 22:36
Yep that fixed it!, thanks a lot!

**Comment by kklee97** [comment] 2019-06-11 08:53
it is working thank you for the fix

**Closed** 2019-06-11 12:24 UTC
Labels: bug, help wanted, missing details

**Comment by mikediachenko** [comment] 2019-06-11 13:22
Gentlemen, after fix for issue #76 was released, I've done `git checkout develop` and `git pull` and script stopped working for me:
`Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/Users/tommy/Documents/GitHub/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/Users/tommy/Documents/GitHub/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

I've run again `python3.7 -m pip install -r requirements.txt` and install geckodriver, but no results. The same error.
Any ideas? I can assume that I am so stupid and done something wrong :)

**Comment by sundowndev** [comment] 2019-06-11 13:26
@mikediachenko This is an issue with geckodriver or selenium. See https://github.com/SeleniumHQ/selenium/issues/3884. Make sure you have the latest version of geckodriver. Also you can checkout to master branch and pull again to ensure you have the latest release of the tool that I just deployed.

If you're still having this issue, open another one please, thank you.

**Comment by mikediachenko** [comment] 2019-06-11 13:28
> @mikediachenko This is an issue with geckodriver or selenium. See [SeleniumHQ/selenium#3884](https://github.com/SeleniumHQ/selenium/issues/3884). Make sure you have the latest version of geckodriver. Also you can checkout to master branch and pull again to ensure you have the latest release of the tool that I just deployed.
> 
> If you're still having this issue, open another one please, thank you.

Got you. Thanks!

**Comment by nelsondisouz** [comment] 2021-05-08 15:04
https://www.google.com/search?tbs=li:1&q=916385772529+OR+%22916385772529%22+OR+%22%2B91+63857+72529%22&num=10&amp;gws_rd=ssl&amp;gl=us
