### ISSUE TITLE
google_api_key is not defined

### ISSUE THREAD

**Issue by 0xNanda** [sundowndev/PhoneInfoga#139] opened 2019-09-29 12:12 UTC
File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "C:\Users\r00tsh3ll\Desktop\maal\PhoneInfoga\scanners\footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "C:\Users\r00tsh3ll\Desktop\maal\PhoneInfoga\lib\googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

PhoneInfoga throws an error like above when I try python phoneinfoga.py -n number

**Comment by sundowndev** [comment] 2019-09-30 08:24
Duplicate of #55

**Closed by sundowndev** 2019-09-30 08:24 UTC
