### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by GLXS00** [sundowndev/PhoneInfoga#107] opened 2019-08-06 21:13 UTC
Keep getting errors and this doesn't seem to be working right. Trying to do a simple search with Phoneinfoga. Can someone tell me what I am doing wrong? [Image](https://imgur.com/a/2OWWouM)

**Comment by shadowownz0** [comment] 2019-08-07 09:35
Did you cp the config file?

**Comment by sundowndev** [comment] 2019-08-07 10:12
You have to create the config file:
```shell
cp config.example.py config.py
```

**Comment by sumsh** [comment] 2019-08-17 04:56
Hey @sundowndev , I am quite new to here. But why don't create a function to create config.py if no config file is currently available?

**Comment by sundowndev** [comment] 2019-08-17 08:10
@sumsh This step is mentioned in the docs.

**Comment by sundowndev** [comment] 2019-08-24 11:03
Duplicate of #70

**Closed by sundowndev** 2019-08-24 11:03 UTC
