### ISSUE TITLE
GOOGLE_ABUSE_EXEMPTION

### ISSUE THREAD

**Issue by karthikamaravadi** [sundowndev/PhoneInfoga#60] opened 2019-06-02 01:25 UTC
I tried searching for GOOGLE_ABUSE_EXEMPTION cookie in browser for mutilple test numbers. However, getting the same issue and also not able to find the cookie in the browser based on https://github.com/sundowndev/PhoneInfoga/wiki/Dealing-with-Google-captcha

PLease let me know if someone found a workaround.

**Comment by whitehatdev11** [comment] 2019-06-02 02:06
I am having the exact same issue.

**Comment by ebubekirtrkr** [comment] 2019-06-02 02:37
I have this issue as well,

**Comment by hunterxxx** [comment] 2019-06-02 07:04
I am not able to find the captcha.

**Comment by AlexSSD7** [comment] 2019-06-02 08:53
no GOOGLE_ABUSE_EXEMPTION cookie at all. same issue.

**Comment by ctZN27328** [comment] 2019-06-02 09:13
i have the same issue, small workaround was opening the link in a browser where i am logged in with google account, searched/refreshed it 5 times, logged out, repeated search 3-5 times then logged in at which point google asked me if i'm a robot, confirmed it and loaded page with cookies

**Comment by Funeoz** [comment] 2019-06-02 10:44
Same here in Firefox

**Comment by sundowndev** [comment] 2019-06-02 11:04
Duplicate of #6

**Closed by sundowndev** 2019-06-02 11:04 UTC
