### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by kcubeterm** [sundowndev/PhoneInfoga#302] opened 2020-04-17 08:19 UTC
Kcubeterm:$ ./phoneinfoga scan -n "+91xxxxxxx"
[i] Scanning phone number +91xxxxxxxxxxx
[i] Running local scan...
[+] Local format: xx
[+] E164 format: +91xxxxxxxxc
[+] International format: 919xxxxxxxxx
[+] Country found: +91 (IN)
[+] Carrier:
[i] Running Numverify.com scan...
[!] An error occured
[!] Get "http://numverify.com/": dial tcp: lookup numverify.com on [::1]:53: read udp [::1]:49447->[::1]:53: read: connection refused

**Comment by sundowndev** [comment] 2020-04-17 08:30
Duplicate of #237 

Are you using Termux too ? Check if the issue resolves when using `sudo`.

If you're not using Termux, questions :

- Did you build from source ?
  - If yes, what version of Go did you use ? If it's <1.13, please consider upgrading to 1.14 and try again
- What is your OS/arch ? Type `uname -a`

**Comment by kcubeterm** [comment] 2020-04-17 11:35
Output of `uname -m` is aarch64 and i didn't compiled it ourselves, i extract arm64 tar archives from releases, i cant use sudo because my phone is not rooted.

**Comment by kcubeterm** [comment] 2020-04-17 11:45
But in aarch (virtualbox os under in termux) , it's works fine, really amazing but doesn't work in termux ,hahahaha

**Comment by sundowndev** [comment] 2020-04-17 12:03
This is a common issue with Termux. Consider using a desktop Linux distro because I don't know how to fix this, and Termux was not intended to be supported explicitly.

**Comment by kcubeterm** [comment] 2020-04-18 03:48
Yes,you are right,any way i am using this amazing tool in my android via virtualbox os, thanks , it's time to close issue

**Closed** 2020-04-18 03:48 UTC

**Comment by savioazure** [comment] 2020-10-09 10:58
Hi sir, i have the same issue here but i am not using termux.

`[+] Country found: +34 (ES)                                                
[+] Carrier: 
[i] Running Numverify.com scan...                                          
[!] An error occurred: Get "http://numverify.com/": dial tcp: lookup numverify.com on [::1]:53: read udp [::1]:41036->[::1]:53: read: connection refused                                                                         
[!] It may be Numverify not finding information about that number, or the number being invalid.                                                       
[i] Generating Google search dork requests...                              
[i] Social media footprints                                                
[+] Link: https://www.google.com/search?q=site%3Afacebook.com+intext%3A%2234604194980%22+OR+intext%3A%22%2B34604194980%22+OR+intext%3A%22604194980%22 
[+] Link: https://www.google.com/search?q=site%3Atwitter.com+intext%3A%2234604194980%22+OR+intext%3A%22%2B34604194980%22+OR+intext%3A%22604194980%22  
[+] Link: https://www.google.com/search?q=site%3Alinked...........................`
