### ISSUE TITLE
 ImportError: No module named parse

### ISSUE THREAD

**Issue by prashantbhatt007** [sundowndev/PhoneInfoga#88] opened 2019-06-20 07:47 UTC
Unable to run phoneinfoga.py script showing following error:-

File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse

**Comment by sundowndev** [comment] 2019-06-20 08:34
Can you retry after doing this : `python3 -m pip install urllib`

Thanks

**Comment by prashantbhatt007** [comment] 2019-06-21 08:50
Tried but showing an error

Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/urllib/

**Comment by anthonyzhub** [comment] 2019-07-03 20:44
Can you show me how you're running the script?

**Comment by c0mm4nd1in3** [comment] 2019-07-29 21:27
> Can you retry after doing this : `python3 -m pip install urllib3`
> 
> Thanks


I tried this and the installation works but It still shows the same error.

**Comment by Angel-Per** [comment] 2019-08-11 20:30
I know I'm about a month-ish late, but I got this issue a few minutes ago, the issue I had was that I was running the script as `python phoneinfoga -n XXX` where XXX is a phone number (and country code). The issue is that I was running it using python2 (I was using `python` instead of `python3`). use python3 in the command to run the script (`python3 phoneinfoga) -n XXX` and it should work just fine.

**Comment by sundowndev** [comment] 2019-08-11 21:22
Thanks for pointing this out @Angel-Per.
@prashantbhatt007 Did you try using python3 executable ?

Closing since it's old/invalid.

**Closed by sundowndev** 2019-08-11 21:22 UTC
Labels: bug, unable to reproduce

**Comment by eqelibari** [comment] 2020-03-30 14:10
i already installed  urllib3 colorama google-search config and still getting the same error after i run "python2 phoneinfoga.py". when i run "python3 phoneinfoga.py" i get the error for no module named colorama, and i have already installed them all.. PhoneInfoga v1.11. Any Help to fix this ?
