### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by iS1rik3** [sundowndev/PhoneInfoga#122] opened 2019-09-03 23:51 UTC
Followed the Install instructions.
Updated Firefox and Geckodriver.
OS:Parrot 4.7

Error Msg:

Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/user/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/user/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by sundowndev** [comment] 2019-09-04 18:55
Duplicate of #91

**Closed by sundowndev** 2019-09-04 18:55 UTC
