### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by RohitRajSharma2002** [sundowndev/PhoneInfoga#125] opened 2019-09-15 12:05 UTC
Came across this error while trying to run phoneinfoga.py -

Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/rohit/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by shiv12340** [comment] 2019-09-17 11:12
same error

**Comment by sundowndev** [comment] 2019-09-17 11:33
Duplicate of #70

**Closed by sundowndev** 2019-09-17 11:33 UTC
