### ISSUE TITLE
json: cannot unmarshal object

### ISSUE THREAD

**Issue by beelzebro** [sundowndev/phoneinfoga#981] opened 2022-01-15 00:59 UTC
error i have:

The following scanners returned errors:
ovh: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber

i ran the following command:

NUMVERIFY_API_KEY=<*redacted*> phoneinfoga scan -n <number here>

i'm assuming that json is supposed to supply some sort of data, which its not. would like to know how i fix this error.

DE:
kali linux
<everything up to date>

**Comment by sundowndev** [comment] 2022-01-15 11:26
Hi, thanks for opening an issue 🙏🏻 

Please don't disclose your API token next time.

I cannot reproduce this issue, without disclosing sensitive data, do you have a sample of phone number that triggers this error ? Which country code is it ?

**Comment by phamducmanh1452001** [comment] 2022-01-15 18:49
> Hi, thanks for opening an issue 🙏🏻
> 
> Please don't disclose your API token next time.
> 
> I cannot reproduce this issue, without disclosing sensitive data, do you have a sample of phone number that triggers this error ? Which country code is it ?

Hi, thank for the helpful tool.
I have the same issues:

ovh: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber

country code is +84 (Vietnam)

**Comment by sundowndev** [comment] 2022-01-16 11:51
Should be fixed in v2.4.1, I'd appreciate if you guys could try it, thanks!

**Comment by ManuelQ59** [comment] 2022-01-16 13:16
And as I do to update to version 2.4.1 having installed and cloned version 2.4.0 on kali linux?.. I delete the directories and clone d new? (example: Git clone......)

**Comment by sundowndev** [comment] 2022-01-16 18:02
> And as I do to update to version 2.4.1 having installed and cloned version 2.4.0 on kali linux?.. I delete the directories and clone d new? (example: Git clone......)

@ManuelQ59 Just run `git pull`

**Comment by beelzebro** [comment] 2022-01-29 16:19
> Hi, thanks for opening an issue 🙏🏻
> 
> Please don't disclose your API token next time.
> 
> I cannot reproduce this issue, without disclosing sensitive data, do you have a sample of phone number that triggers this error ? Which country code is it ?

1734277####

**Comment by sundowndev** [comment] 2022-01-29 16:57
@beelzebro Did you try the latest version ?

**Comment by beelzebro** [comment] 2022-04-18 20:51
yes

**Comment by sauhardo2020** [comment] 2022-07-31 05:20
The Error is still showing for me how do i fix it?

**Comment by AtillaDev** [comment] 2022-08-20 16:56
Hey I still have the same error as the first message the country code is +359

**Comment by haqthat** [comment] 2022-08-23 17:52
I too am receiving OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber
Country Code +1

**Comment by Debuging-Dev** [comment] 2022-08-31 10:59
> error i have:
> 
> The following scanners returned errors: ovh: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber
> 
> i ran the following command:
> 
> NUMVERIFY_API_KEY=<_redacted_> phoneinfoga scan -n
> 
> i'm assuming that json is supposed to supply some sort of data, which its not. would like to know how i fix this error.
> 
> DE: kali linux

I have the same issues for Romania numbers (+40)

**Comment by sundowndev** [comment] 2022-08-31 20:15
Duplicate of #1106

**Closed by sundowndev** 2022-08-31 20:15 UTC

**Comment by 53845714nF** [comment] 2022-09-04 20:56
Sorry I still have this Issue on Version v2.7.0 with German numbers (+49).

**Comment by Codezero012** [comment] 2022-09-08 04:27
Hi, I still have the same error as the first message the country code is +57
