### ISSUE TITLE
Error while installing "requirements"!!!

### ISSUE THREAD

**Issue by ratul3123** [sundowndev/PhoneInfoga#396] opened 2020-06-18 11:12 UTC
"`~/PhoneInfoga# python3 -m pip install -r requirements.txt`"
This command is not working anymore. It's resulting in an error saying,
"`/usr/bin/python3: No module named pip`"
Please help me install the requirements of PhoneInfoga.

**Comment by sundowndev** [comment] 2020-06-18 11:55
You didn't install the project properly. This project does not require Python anymore. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).

**Comment by ratul3123** [comment] 2020-06-18 23:29
I'm using it on Kali Linux. Does it support on Kali anymore?

**Comment by sundowndev** [comment] 2020-06-19 07:16
Yes.

**Comment by ratul3123** [comment] 2020-06-19 11:08
Now this error is happening_

`bash: ./phoneinfoga: cannot execute binary file: Exec format error`

**Comment by sundowndev** [comment] 2020-06-19 11:17
Can you check the output of `echo "$(uname -s)_$(uname -m)"` in your terminal and see if it's available on the GitHub release page? https://github.com/sundowndev/PhoneInfoga/releases

**Comment by ratul3123** [comment] 2020-06-26 05:44
Thankfully it worked. Thank you so much. But I still have a question. What if I get blacklisted by Google?

**Comment by sundowndev** [comment] 2020-06-26 07:48
Alright, can you please tell me what fixed the problem?

> What if I get blacklisted by Google?

Can't you just complete the captcha in your browser ?

**Comment by ratul3123** [comment] 2020-06-26 19:12
Hehehehe....Sorry....!!! And thank you so much!!

**Comment by sundowndev** [comment] 2020-07-05 15:26
Closing since the issue is resolved

**Closed by sundowndev** 2020-07-05 15:26 UTC
