### ISSUE TITLE
[i] ---- Web pages footprints ---- [i] Searching for footprints on web pages... (limit=10) Traceback (most recent call last):   File "phoneinfoga.py", line 89, in <module>     main()   File "phoneinfoga.py", line 70, in main     scanNumber(args.number)   File "phoneinfoga.py", line 37, in scanNumber     osintScan(number)   File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 173, in osintScan     for result in search(req, stop=10):   File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 22, in search     if google_api_key and google_cx_id: NameError: name 'google_api_key' is not defined

### ISSUE THREAD

**Issue by nitroxnoob** [sundowndev/PhoneInfoga#69] opened 2019-06-08 11:05 UTC
**Describe the bug**

**To Reproduce**
What command did you run ? (hide any personal information such as phone number or ip address)

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 18.04 ...]
 - Python exact version (run `python --version`)

**Additional context**

**Comment by nitroxnoob** [comment] 2019-06-08 11:06
Please help me out....

**Comment by sundowndev** [comment] 2019-06-08 11:55
Just read the wiki.

Duplicate of #67

**Closed by sundowndev** 2019-06-08 11:55 UTC
