### ISSUE TITLE
Cant get past Google Abuse Exemption

### ISSUE THREAD

**Issue by JetHeller** [sundowndev/PhoneInfoga#63] opened 2019-06-06 05:46 UTC
**Describe the bug**
The CAPTCHA never comes up

**To Reproduce**
proxychains python3 phoneinfoga.py -n countrycode+# --recon

**Expected behavior**
When I got the GOOGLE_ABUSE_EXEMPTION= I followed the url and it did not produce a CAPCHA. I tried all of the steps in the troubleshooting section.

**Screenshots (optional)**

**Desktop (please complete the following information):**
Linux kali 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

Python 3.7.3rc1

**Additional context**
I am running VPN and TOR

**Comment by iLevye** [comment] 2019-06-06 16:06
Im not running any vpn or something. I'm having same issue on mac os. I tried different browsers.

**Comment by r3vy** [comment] 2019-06-07 21:41
Seems to be the only thing hold this back, I tried everything. It seems it runs almost on pure luck.

**Comment by djhedin** [comment] 2019-06-08 03:25
Same here, unable to trigger CAPTCHA. The requested cookie is also not present.

**Comment by sundowndev** [comment] 2019-06-08 10:53
Duplicate of #6

**Closed by sundowndev** 2019-06-08 10:53 UTC
Labels: duplicate

**Comment by aeschylus396** [comment] 2020-05-02 10:09
What I do bro it show
