### ISSUE TITLE
Scanners Numverify, ovh, google search error..! 

### ISSUE THREAD

**Issue by noismi** [sundowndev/PhoneInfoga#307] opened 2020-04-20 07:49 UTC
![Screenshot_20200420-144358~2](https://user-images.githubusercontent.com/63945537/79727116-10a52900-8316-11ea-9f8e-2b0de28327f9.png)

how to get more information from a phone number

**Comment by arkadeepdeb** [comment] 2020-04-21 20:24
Yes i am having the same issue. Please tell a fix for this..

**Comment by sundowndev** [comment] 2020-04-21 21:51
Duplicate of #302 

>This is a common issue with Termux. Consider using a desktop Linux distro instead because I don't know how to fix this, and Termux isn't intended to be explicitly supported.

**Closed by sundowndev** 2020-04-21 21:51 UTC
