### ISSUE TITLE
Where is the file to put Numverify API key 

### ISSUE THREAD

**Issue by WelskyOG** [sundowndev/phoneinfoga#1008] opened 2022-02-22 15:40 UTC
Hey guys. I am fairly new to Linux based OS. I am getting into Linode and Ubuntu 20.04 for my new job in IT. I am currently trying to find the file where I put the Numverify API key into or if I am suppose to create it? I read somewhere there is an env-file that it goes into, but no where did it specify where that file is located. Not sure if it is in the git clone directory or somewhere in /var/lib/docker directory. If there is a simple command to create the file and paste the key inside, that would be most helpful. Again, I am fairly new to Linux but getting the hang of it fairly quickly. Thanks!

P.S. I also downloaded phoneinfoga using the docker installation on ubuntu.

**Comment by sundowndev** [comment] 2022-02-24 10:13
Duplicate of https://github.com/sundowndev/phoneinfoga/issues/983

**Closed by sundowndev** 2022-02-24 10:13 UTC
