### ISSUE TITLE
Getting Error after installing PhoneInfoga and all the python libraries.

### ISSUE THREAD

**Issue by parteeksingh005** [sundowndev/PhoneInfoga#89] opened 2019-06-21 10:12 UTC
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/opt/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by parteeksingh005** [comment] 2019-06-21 10:20
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/opt/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse


Now getting this error.

**Comment by RIS33** [comment] 2019-06-24 21:40
> Traceback (most recent call last):
> File "phoneinfoga.py", line 17, in 
> from lib.googlesearch import closeBrowser
> File "/opt/PhoneInfoga/lib/googlesearch.py", line 15, in 
> from config import *
> ModuleNotFoundError: No module named 'config'

I have this problem too

**Comment by sundowndev** [comment] 2019-06-27 19:33
Duplicate of #70

**Closed by sundowndev** 2019-06-27 19:33 UTC
Labels: duplicate

**Comment by RobinRana** [comment] 2019-07-26 16:29
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/Desktop/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

i have problem help me anyone

**Comment by ashleyr889** [comment] 2019-08-21 02:07
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config

Getting the same message as well... How can I fix it?

**Comment by 4NONYM4U5** [comment] 2019-08-29 14:56
Run these commands :
sudo pip install google-search
sudo pip install config

**Comment by StyFx** [comment] 2019-09-04 19:36
no modul named Config

**Comment by RobinRana** [comment] 2019-09-04 19:49
Thanks i go to try

**Comment by jaderoe** [comment] 2019-09-08 12:11
it works thanks #4NONYM4U5

**Comment by raj8887** [comment] 2020-03-14 15:28
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse


plz help me

**Comment by LOKESHG1234** [comment] 2020-04-07 07:28
Traceback (most recent call last):
File "phoneinfoga.py", line 17, in
from lib.googlesearch import closeBrowser
File "/root/PhoneInfoga/lib/googlesearch.py", line 11, in
from urllib.parse import urlencode
ImportError: No module named parse
Please help me

**Comment by sundowndev** [comment] 2020-04-07 09:11
@LOKESHG1234 Seems like you followed a tutorial to use the tool, that tutorial is not longer updated. Please read documentation.

**Comment by bonga187** [comment] 2022-02-10 20:20
How to run phoneinfoga after installation
